{{- if .Values.global.istio.ingress }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-istio-casa
  namespace: {{.Release.Namespace}}
  labels:
    APP_NAME: casa
{{ include "casa.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
spec:
{{- if and (.Values.global.istio.gateways) (not .Values.global.istio.ingress) }}
  gateways:
{{ toYaml .Values.global.istio.gateways | indent 2 }}
{{- else }}
  gateways:
  - {{ .Release.Name }}-global-gtw
{{- end }}
  hosts:
  - {{ .Values.global.fqdn }}
  http:
  - name: {{ .Release.Name }}-istio-casa
    match:
    - uri:
        prefix: /casa
    route:
    - destination:
        host: {{ .Values.global.casa.casaServiceName }}.{{.Release.Namespace}}.svc.cluster.local
        port:
          number: 8080
      weight: 100
{{- end }}
