name: Activate Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  publish_binary_packages:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: set nightly version
      id: nightly
      continue-on-error: false
      if: ${{ github.event_name }} == 'schedule' || ${{ github.event.inputs.nightly }} == 'true'
      run: |
        VERSION=`curl  "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-` 
        echo $VERSION
        curl -sSL https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.tar.gz -o gh_${VERSION}_linux_amd64.tar.gz
        tar xvf gh_${VERSION}_linux_amd64.tar.gz
        sudo cp gh_${VERSION}_linux_amd64/bin/gh /usr/local/bin/
        gh version
        echo "${{ secrets.MOWORKFLOWTOKEN }}" | gh auth login --with-token
        NIGHTLY_VERSION=$(cat docker-casa/Dockerfile | grep "ENV GLUU_VERSION" | awk -F "[=-]" '{print $2}')
        # if Nightly version is equal to 5.0.0 then increment the patch version
        if [[ $NIGHTLY_VERSION == "5.0.0" ]]; then
          TAGS=$(gh release list -L 1000 -R ${{ github.repository }} | grep -o '^\v.*'| grep -v Draft | cut -f 1 | sed '/-/!{s/$/_/}' | sort -V | sed 's/_$//')
          PATCH_NUMBER=$(echo "${TAGS}" | grep -v -- "nightly" | tail -1 | tr -d "v5.0.0-")
          PATCH_NUMBER=$((PATCH_NUMBER+1))
          NIGHTLY_VERSION="5.0.0-${PATCH_NUMBER}"
        fi
        gh release delete v${NIGHTLY_VERSION}.nightly --cleanup-tag --yes || echo "v${NIGHTLY_VERSION}.nightly" does not exist
        gh release delete v${NIGHTLY_VERSION}.nightly --cleanup-tag --yes || echo "v${NIGHTLY_VERSION}.nightly" does not exist
        git push --delete origin v${NIGHTLY_VERSION}.nightly || echo "v${NIGHTLY_VERSION}.nightly" does not exist
        gh release create v${NIGHTLY_VERSION}.nightly --generate-notes --prerelease --title "v${NIGHTLY_VERSION}.nightly"