name: rancher-partner-charts
# This posts the latest chart to rancher/partner-charts
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  publish:
    name: Publish on rancher partner charts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set up Python 3.8
      uses: actions/setup-python@v3.0.0
      with:
        python-version: 3.8

      - name: analyze chart
        run: |
          sudo bash automation/janssen_helm_chart/prepare_chart.sh

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.MOAUTO_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MOAUTO_GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Get latest tag
        id: previoustag
        run: |
          echo "::set-output name=tag::$(curl https://api.github.com/repos/${{ github.repository }}/releases -s | grep "tag_name" | cut -d '"' -f 4 | grep -o '^\v.*' | head -n 1)"
          echo "::set-output name=version::$(curl https://api.github.com/repos/${{ github.repository }}/releases -s | grep "tag_name" | cut -d '"' -f 4 | grep -o '^\v.*' | head -n 1 | cut -d 'v' -f 2)"
      - name: Configure Git
        run: |
          git config user.name "mo-auto"
          git config user.email "54212639+mo-auto@users.noreply.github.com"
          git config --global user.signingkey "${{ steps.import_gpg.outputs.keyid }}"
          # open branch in rancher-partner
          git clone https://github.com/rancher/partner-charts.git
          cd partner-charts
          git remote set-url origin https://mo-auto:${{ secrets.MOWORKFLOWTOKEN }}@github.com/rancher/partner-charts.git
          git switch -c gluu-flex-main-source origin/main-source
          cp ../automation/rancher-partner-charts/package.yaml ./packages/gluu/package.yaml
          export PACKAGE=gluu
          make prepare
          cp ../automation/rancher-partner-charts/app-readme.md ./packages/gluu/charts/app-readme.md
          cp ../automation/rancher-partner-charts/questions.yaml ./packages/gluu/charts/questions.yaml
          make patch
          make clean
          git add -A
          git commit -S -s -m "feat(gluu): patch helm package"
          make charts
          git add -A
          git commit -S -s -m "feat(gluu): chart helm package"
          git push --set-upstream origin gluu-flex-main-source
          MESSAGE="feat(gluu): update Gluu helm partner chart"
          BODY="This is an automated message propagated by a release in the parent Gluu chart."
          echo "${{ secrets.MOAUTO4_WORKFLOW_TOKEN }}" > token.txt
          gh auth login --with-token < token.txt
          PR=$(gh pr create --base "main-source" --body "${BODY}" --title "${MESSAGE}")        
